version: '3'

volumes:
  postgres_data:
    driver: local

services:
  postgres:
    image: docker.io/bitnami/postgresql:11
    volumes:
      - postgres_data:/bitnami/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
  keycloak:
    image: docker.io/bitnami/keycloak:25
    volumes:
      - ./disable-theme-cache.cli:/docker-entrypoint-initdb.d/disable-theme-cache.cli
      - ./themes/befritco/:/opt/bitnami/keycloak/themes/befritco/
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_LOGLEVEL: INFO
      ROOT_LOGLEVEL: INFO
      KEYCLOAK_EXTRA_ARGS_PREPENDED: --spi-theme-welcome-theme=befritco
    command:
      - /opt/bitnami/scripts/keycloak/run.sh
      - start-dev
      # - --spi-theme-welcome-theme=befritco
    ports:
      - 8443:8443
      - 8080:8080
    depends_on:
      - postgres
